#ifndef HILLCOUNTER_GLOBAL_H
#define HILLCOUNTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HILLCOUNTER_LIBRARY)
#  define HILLCOUNTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HILLCOUNTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HILLCOUNTER_GLOBAL_H
