#ifndef TURNTYPESCOUNTER_GLOBAL_H
#define TURNTYPESCOUNTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TURNTYPESCOUNTER_LIBRARY)
#  define TURNTYPESCOUNTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TURNTYPESCOUNTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TURNTYPESCOUNTER_GLOBAL_H
