#ifndef HILLTYPESCOUNTER_GLOBAL_H
#define HILLTYPESCOUNTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HILLTYPESCOUNTER_LIBRARY)
#  define HILLTYPESCOUNTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HILLTYPESCOUNTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HILLTYPESCOUNTER_GLOBAL_H
